### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by JonathanEsposito** [Mte90/CMB2-User-Search-field#2]
Hi! There seems to be some error in the javascript. But I can't figure out how to fix this.. :/

line 210:  window.cmb2_user_search<?php echo $field->args( 'id' ) ?> = new UserSearchView<?php echo str_replace( '-', '_', $field->args( 'id' ) ) ?>();

gives me "Uncaught ReferenceError: Invalid left-hand side in assignment" in the console and nothing much to look at on the edit-post page:
<img width="527" alt="screen shot 2015-11-08 at 14 01 38" src="https://cloud.githubusercontent.com/assets/41599/11020523/4633b75e-8621-11e5-9140-dd318408e288.png">

I'm using wp 4.3.1 and the cmb2 plugin 2.1.2

Grazie in anticipo :D

**Comment by Mte90** [comment]
the error is in the javascript console?
what is the html output generated in that page ?

**Comment by JonathanEsposito** [comment]
The error appears in the javascript console idd.
To display the Metabox on the admin page, I used "prefix-user" as id like you suggested, and it gives this html output on the page

```
          window.cmb2_user_searchprefix-user = new UserSearchViewprefix_user();

          $('.cmb-type-user-search-text.cmb2-id-prefix-user .cmb-th label').after('<div title="' + l10n.find + '" style="position:relative;left:30%;color: #999;cursor: pointer;" class="dashicons dashicons-search"></div>');

          $('.cmb-type-user-search-text.cmb2-id-prefix-user .cmb-th .dashicons-search').on('click', openSearch);

          function openSearch(evt) {
            var search = window.cmb2_user_searchprefix-user;
            search.$idInput = $(evt.currentTarget).parents('.cmb-type-user-search-text').find('.cmb-td input[type="text"]');
            search.roles = search.$idInput.data('roles');
            search.selectType = 'radio' === search.$idInput.data('selecttype') ? 'radio' : 'checkbox';

            search.trigger('open');
```

I just solved it by replacing "echo $field->args( 'id' )" with "echo str_replace( '-', '_', $field->args( 'id' ) )" on both line 210 (before = ) and line 217 as on these lines the dashes were not replaced by an underscore

**Comment by Mte90** [comment]
is the same of https://github.com/Mte90/CMB2-User-Search-field/issues/1 that i've already fixed: https://github.com/Mte90/CMB2-User-Search-field/commit/39fef3222abf0dff1f5b45f9eeb6aec46f8b83fb

**Comment by JonathanEsposito** [comment]
No no, I am using the latest version which has this latest fix. As you can see on the html output, "UserSearchViewprefix_user" has an underscore in stead of the dash from the $field->args( 'id' ) (which is "prefix-user").
But it doesn't seem to fix the "Uncaught ReferenceError: Invalid left-hand side in assignment"-error..

**Comment by Mte90** [comment]
the dash in javascript cannot be used for variable and other stuff while the underscore yes.
In the last fix I've missed that lines, now is fixed.
thanks you for the issues!

**Comment by JonathanEsposito** [comment]
Splendid! Thanks for the super quick response!
